### ISSUE TITLE
gitee太坑了，被锁定仓库删不了。

### ISSUE THREAD

**Issue by KyonCN** [Tyrone2333/giteeDeleteAccount#1]
fork了几个敏感仓库被锁定无法删除，账号下有仓库没发销号，然后发邮件官方也不理，真是死循环。
大佬你删号成功了吗

**Comment by Tyrone2333** [comment]
网页和接口都不能删除吗? 那基本无解了...

**Comment by KyonCN** [comment]
> 网页和接口都不能删除吗? 那基本无解了...

两种方法都试了下不行，确实坑。 
不过大佬的方法确实简单，另一个用python写的删库项目用起来很麻烦。
